// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: writer/writer.proto

package writer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteFitInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFitInputRequest) Reset() {
	*x = WriteFitInputRequest{}
	mi := &file_writer_writer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFitInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFitInputRequest) ProtoMessage() {}

func (x *WriteFitInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writer_writer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFitInputRequest.ProtoReflect.Descriptor instead.
func (*WriteFitInputRequest) Descriptor() ([]byte, []int) {
	return file_writer_writer_proto_rawDescGZIP(), []int{0}
}

func (x *WriteFitInputRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WriteFitInputRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *WriteFitInputRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFitInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     string                 `protobuf:"bytes,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	FitInputId    string                 `protobuf:"bytes,2,opt,name=fit_input_id,json=fitInputId,proto3" json:"fit_input_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFitInputResponse) Reset() {
	*x = WriteFitInputResponse{}
	mi := &file_writer_writer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFitInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFitInputResponse) ProtoMessage() {}

func (x *WriteFitInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writer_writer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFitInputResponse.ProtoReflect.Descriptor instead.
func (*WriteFitInputResponse) Descriptor() ([]byte, []int) {
	return file_writer_writer_proto_rawDescGZIP(), []int{1}
}

func (x *WriteFitInputResponse) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *WriteFitInputResponse) GetFitInputId() string {
	if x != nil {
		return x.FitInputId
	}
	return ""
}

var File_writer_writer_proto protoreflect.FileDescriptor

const file_writer_writer_proto_rawDesc = "" +
	"\n" +
	"\x13writer/writer.proto\x12\x06writer\"b\n" +
	"\x14WriteFitInputRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"X\n" +
	"\x15WriteFitInputResponse\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\tR\tsectionId\x12 \n" +
	"\ffit_input_id\x18\x02 \x01(\tR\n" +
	"fitInputId2V\n" +
	"\x06Writer\x12L\n" +
	"\rWriteFitInput\x12\x1c.writer.WriteFitInputRequest\x1a\x1d.writer.WriteFitInputResponseB'Z%ml-models-api/protos/protos_go/writerb\x06proto3"

var (
	file_writer_writer_proto_rawDescOnce sync.Once
	file_writer_writer_proto_rawDescData []byte
)

func file_writer_writer_proto_rawDescGZIP() []byte {
	file_writer_writer_proto_rawDescOnce.Do(func() {
		file_writer_writer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_writer_writer_proto_rawDesc), len(file_writer_writer_proto_rawDesc)))
	})
	return file_writer_writer_proto_rawDescData
}

var file_writer_writer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_writer_writer_proto_goTypes = []any{
	(*WriteFitInputRequest)(nil),  // 0: writer.WriteFitInputRequest
	(*WriteFitInputResponse)(nil), // 1: writer.WriteFitInputResponse
}
var file_writer_writer_proto_depIdxs = []int32{
	0, // 0: writer.Writer.WriteFitInput:input_type -> writer.WriteFitInputRequest
	1, // 1: writer.Writer.WriteFitInput:output_type -> writer.WriteFitInputResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_writer_writer_proto_init() }
func file_writer_writer_proto_init() {
	if File_writer_writer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_writer_writer_proto_rawDesc), len(file_writer_writer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_writer_writer_proto_goTypes,
		DependencyIndexes: file_writer_writer_proto_depIdxs,
		MessageInfos:      file_writer_writer_proto_msgTypes,
	}.Build()
	File_writer_writer_proto = out.File
	file_writer_writer_proto_goTypes = nil
	file_writer_writer_proto_depIdxs = nil
}
