// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: models/ant_colony.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AntColonyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           int32                  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntColonyPoint) Reset() {
	*x = AntColonyPoint{}
	mi := &file_models_ant_colony_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntColonyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntColonyPoint) ProtoMessage() {}

func (x *AntColonyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_models_ant_colony_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntColonyPoint.ProtoReflect.Descriptor instead.
func (*AntColonyPoint) Descriptor() ([]byte, []int) {
	return file_models_ant_colony_proto_rawDescGZIP(), []int{0}
}

func (x *AntColonyPoint) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *AntColonyPoint) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AntColonyPoint) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type AntColonySegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromP         *AntColonyPoint        `protobuf:"bytes,1,opt,name=from_p,json=fromP,proto3" json:"from_p,omitempty"`
	ToP           *AntColonyPoint        `protobuf:"bytes,2,opt,name=to_p,json=toP,proto3" json:"to_p,omitempty"`
	Distance      float64                `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Pheromone     *float64               `protobuf:"fixed64,4,opt,name=pheromone,proto3,oneof" json:"pheromone,omitempty"`
	Probability   *float64               `protobuf:"fixed64,5,opt,name=probability,proto3,oneof" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntColonySegment) Reset() {
	*x = AntColonySegment{}
	mi := &file_models_ant_colony_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntColonySegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntColonySegment) ProtoMessage() {}

func (x *AntColonySegment) ProtoReflect() protoreflect.Message {
	mi := &file_models_ant_colony_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntColonySegment.ProtoReflect.Descriptor instead.
func (*AntColonySegment) Descriptor() ([]byte, []int) {
	return file_models_ant_colony_proto_rawDescGZIP(), []int{1}
}

func (x *AntColonySegment) GetFromP() *AntColonyPoint {
	if x != nil {
		return x.FromP
	}
	return nil
}

func (x *AntColonySegment) GetToP() *AntColonyPoint {
	if x != nil {
		return x.ToP
	}
	return nil
}

func (x *AntColonySegment) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *AntColonySegment) GetPheromone() float64 {
	if x != nil && x.Pheromone != nil {
		return *x.Pheromone
	}
	return 0
}

func (x *AntColonySegment) GetProbability() float64 {
	if x != nil && x.Probability != nil {
		return *x.Probability
	}
	return 0
}

type AntColonyTrail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*AntColonySegment    `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	TotalDistance *float64               `protobuf:"fixed64,2,opt,name=total_distance,json=totalDistance,proto3,oneof" json:"total_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntColonyTrail) Reset() {
	*x = AntColonyTrail{}
	mi := &file_models_ant_colony_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntColonyTrail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntColonyTrail) ProtoMessage() {}

func (x *AntColonyTrail) ProtoReflect() protoreflect.Message {
	mi := &file_models_ant_colony_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntColonyTrail.ProtoReflect.Descriptor instead.
func (*AntColonyTrail) Descriptor() ([]byte, []int) {
	return file_models_ant_colony_proto_rawDescGZIP(), []int{2}
}

func (x *AntColonyTrail) GetSegments() []*AntColonySegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *AntColonyTrail) GetTotalDistance() float64 {
	if x != nil && x.TotalDistance != nil {
		return *x.TotalDistance
	}
	return 0
}

type AntColonyTrailMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matrix        []*AntColonyTrail      `protobuf:"bytes,1,rep,name=matrix,proto3" json:"matrix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntColonyTrailMatrix) Reset() {
	*x = AntColonyTrailMatrix{}
	mi := &file_models_ant_colony_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntColonyTrailMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntColonyTrailMatrix) ProtoMessage() {}

func (x *AntColonyTrailMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_models_ant_colony_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntColonyTrailMatrix.ProtoReflect.Descriptor instead.
func (*AntColonyTrailMatrix) Descriptor() ([]byte, []int) {
	return file_models_ant_colony_proto_rawDescGZIP(), []int{3}
}

func (x *AntColonyTrailMatrix) GetMatrix() []*AntColonyTrail {
	if x != nil {
		return x.Matrix
	}
	return nil
}

type AntColonyCollectionOfAntsTrails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trails        []*AntColonyTrail      `protobuf:"bytes,1,rep,name=trails,proto3" json:"trails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntColonyCollectionOfAntsTrails) Reset() {
	*x = AntColonyCollectionOfAntsTrails{}
	mi := &file_models_ant_colony_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntColonyCollectionOfAntsTrails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntColonyCollectionOfAntsTrails) ProtoMessage() {}

func (x *AntColonyCollectionOfAntsTrails) ProtoReflect() protoreflect.Message {
	mi := &file_models_ant_colony_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntColonyCollectionOfAntsTrails.ProtoReflect.Descriptor instead.
func (*AntColonyCollectionOfAntsTrails) Descriptor() ([]byte, []int) {
	return file_models_ant_colony_proto_rawDescGZIP(), []int{4}
}

func (x *AntColonyCollectionOfAntsTrails) GetTrails() []*AntColonyTrail {
	if x != nil {
		return x.Trails
	}
	return nil
}

type AntColonyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntColonyPointRequest) Reset() {
	*x = AntColonyPointRequest{}
	mi := &file_models_ant_colony_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntColonyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntColonyPointRequest) ProtoMessage() {}

func (x *AntColonyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_ant_colony_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntColonyPointRequest.ProtoReflect.Descriptor instead.
func (*AntColonyPointRequest) Descriptor() ([]byte, []int) {
	return file_models_ant_colony_proto_rawDescGZIP(), []int{5}
}

func (x *AntColonyPointRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AntColonyPointRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type AntColonyRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Points        []*AntColonyPointRequest `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntColonyRequest) Reset() {
	*x = AntColonyRequest{}
	mi := &file_models_ant_colony_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntColonyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntColonyRequest) ProtoMessage() {}

func (x *AntColonyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_ant_colony_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntColonyRequest.ProtoReflect.Descriptor instead.
func (*AntColonyRequest) Descriptor() ([]byte, []int) {
	return file_models_ant_colony_proto_rawDescGZIP(), []int{6}
}

func (x *AntColonyRequest) GetPoints() []*AntColonyPointRequest {
	if x != nil {
		return x.Points
	}
	return nil
}

type AntColonyResponse struct {
	state                  protoimpl.MessageState           `protogen:"open.v1"`
	FirstTrail             *AntColonyTrail                  `protobuf:"bytes,1,opt,name=first_trail,json=firstTrail,proto3" json:"first_trail,omitempty"`
	LastTrail              *AntColonyTrail                  `protobuf:"bytes,2,opt,name=last_trail,json=lastTrail,proto3" json:"last_trail,omitempty"`
	CollectionOfAntsTrails *AntColonyCollectionOfAntsTrails `protobuf:"bytes,3,opt,name=collection_of_ants_trails,json=collectionOfAntsTrails,proto3" json:"collection_of_ants_trails,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AntColonyResponse) Reset() {
	*x = AntColonyResponse{}
	mi := &file_models_ant_colony_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntColonyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntColonyResponse) ProtoMessage() {}

func (x *AntColonyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_ant_colony_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntColonyResponse.ProtoReflect.Descriptor instead.
func (*AntColonyResponse) Descriptor() ([]byte, []int) {
	return file_models_ant_colony_proto_rawDescGZIP(), []int{7}
}

func (x *AntColonyResponse) GetFirstTrail() *AntColonyTrail {
	if x != nil {
		return x.FirstTrail
	}
	return nil
}

func (x *AntColonyResponse) GetLastTrail() *AntColonyTrail {
	if x != nil {
		return x.LastTrail
	}
	return nil
}

func (x *AntColonyResponse) GetCollectionOfAntsTrails() *AntColonyCollectionOfAntsTrails {
	if x != nil {
		return x.CollectionOfAntsTrails
	}
	return nil
}

var File_models_ant_colony_proto protoreflect.FileDescriptor

const file_models_ant_colony_proto_rawDesc = "" +
	"\n" +
	"\x17models/ant_colony.proto\x12\tml_models\">\n" +
	"\x0eAntColonyPoint\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\"\xf6\x01\n" +
	"\x10AntColonySegment\x120\n" +
	"\x06from_p\x18\x01 \x01(\v2\x19.ml_models.AntColonyPointR\x05fromP\x12,\n" +
	"\x04to_p\x18\x02 \x01(\v2\x19.ml_models.AntColonyPointR\x03toP\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x01R\bdistance\x12!\n" +
	"\tpheromone\x18\x04 \x01(\x01H\x00R\tpheromone\x88\x01\x01\x12%\n" +
	"\vprobability\x18\x05 \x01(\x01H\x01R\vprobability\x88\x01\x01B\f\n" +
	"\n" +
	"_pheromoneB\x0e\n" +
	"\f_probability\"\x88\x01\n" +
	"\x0eAntColonyTrail\x127\n" +
	"\bsegments\x18\x01 \x03(\v2\x1b.ml_models.AntColonySegmentR\bsegments\x12*\n" +
	"\x0etotal_distance\x18\x02 \x01(\x01H\x00R\rtotalDistance\x88\x01\x01B\x11\n" +
	"\x0f_total_distance\"I\n" +
	"\x14AntColonyTrailMatrix\x121\n" +
	"\x06matrix\x18\x01 \x03(\v2\x19.ml_models.AntColonyTrailR\x06matrix\"T\n" +
	"\x1fAntColonyCollectionOfAntsTrails\x121\n" +
	"\x06trails\x18\x01 \x03(\v2\x19.ml_models.AntColonyTrailR\x06trails\"3\n" +
	"\x15AntColonyPointRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"L\n" +
	"\x10AntColonyRequest\x128\n" +
	"\x06points\x18\x01 \x03(\v2 .ml_models.AntColonyPointRequestR\x06points\"\xf0\x01\n" +
	"\x11AntColonyResponse\x12:\n" +
	"\vfirst_trail\x18\x01 \x01(\v2\x19.ml_models.AntColonyTrailR\n" +
	"firstTrail\x128\n" +
	"\n" +
	"last_trail\x18\x02 \x01(\v2\x19.ml_models.AntColonyTrailR\tlastTrail\x12e\n" +
	"\x19collection_of_ants_trails\x18\x03 \x01(\v2*.ml_models.AntColonyCollectionOfAntsTrailsR\x16collectionOfAntsTrailsB'Z%ml-models-api/protos/protos_go/modelsb\x06proto3"

var (
	file_models_ant_colony_proto_rawDescOnce sync.Once
	file_models_ant_colony_proto_rawDescData []byte
)

func file_models_ant_colony_proto_rawDescGZIP() []byte {
	file_models_ant_colony_proto_rawDescOnce.Do(func() {
		file_models_ant_colony_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_ant_colony_proto_rawDesc), len(file_models_ant_colony_proto_rawDesc)))
	})
	return file_models_ant_colony_proto_rawDescData
}

var file_models_ant_colony_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_models_ant_colony_proto_goTypes = []any{
	(*AntColonyPoint)(nil),                  // 0: ml_models.AntColonyPoint
	(*AntColonySegment)(nil),                // 1: ml_models.AntColonySegment
	(*AntColonyTrail)(nil),                  // 2: ml_models.AntColonyTrail
	(*AntColonyTrailMatrix)(nil),            // 3: ml_models.AntColonyTrailMatrix
	(*AntColonyCollectionOfAntsTrails)(nil), // 4: ml_models.AntColonyCollectionOfAntsTrails
	(*AntColonyPointRequest)(nil),           // 5: ml_models.AntColonyPointRequest
	(*AntColonyRequest)(nil),                // 6: ml_models.AntColonyRequest
	(*AntColonyResponse)(nil),               // 7: ml_models.AntColonyResponse
}
var file_models_ant_colony_proto_depIdxs = []int32{
	0, // 0: ml_models.AntColonySegment.from_p:type_name -> ml_models.AntColonyPoint
	0, // 1: ml_models.AntColonySegment.to_p:type_name -> ml_models.AntColonyPoint
	1, // 2: ml_models.AntColonyTrail.segments:type_name -> ml_models.AntColonySegment
	2, // 3: ml_models.AntColonyTrailMatrix.matrix:type_name -> ml_models.AntColonyTrail
	2, // 4: ml_models.AntColonyCollectionOfAntsTrails.trails:type_name -> ml_models.AntColonyTrail
	5, // 5: ml_models.AntColonyRequest.points:type_name -> ml_models.AntColonyPointRequest
	2, // 6: ml_models.AntColonyResponse.first_trail:type_name -> ml_models.AntColonyTrail
	2, // 7: ml_models.AntColonyResponse.last_trail:type_name -> ml_models.AntColonyTrail
	4, // 8: ml_models.AntColonyResponse.collection_of_ants_trails:type_name -> ml_models.AntColonyCollectionOfAntsTrails
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_models_ant_colony_proto_init() }
func file_models_ant_colony_proto_init() {
	if File_models_ant_colony_proto != nil {
		return
	}
	file_models_ant_colony_proto_msgTypes[1].OneofWrappers = []any{}
	file_models_ant_colony_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_ant_colony_proto_rawDesc), len(file_models_ant_colony_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_ant_colony_proto_goTypes,
		DependencyIndexes: file_models_ant_colony_proto_depIdxs,
		MessageInfos:      file_models_ant_colony_proto_msgTypes,
	}.Build()
	File_models_ant_colony_proto = out.File
	file_models_ant_colony_proto_goTypes = nil
	file_models_ant_colony_proto_depIdxs = nil
}
