// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: models/pythagorean.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PythagoreanPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []float64              `protobuf:"fixed64,1,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythagoreanPoint) Reset() {
	*x = PythagoreanPoint{}
	mi := &file_models_pythagorean_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythagoreanPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythagoreanPoint) ProtoMessage() {}

func (x *PythagoreanPoint) ProtoReflect() protoreflect.Message {
	mi := &file_models_pythagorean_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythagoreanPoint.ProtoReflect.Descriptor instead.
func (*PythagoreanPoint) Descriptor() ([]byte, []int) {
	return file_models_pythagorean_proto_rawDescGZIP(), []int{0}
}

func (x *PythagoreanPoint) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type PythagoreanGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*PythagoreanPoint    `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	NPoints       int32                  `protobuf:"varint,2,opt,name=n_points,json=nPoints,proto3" json:"n_points,omitempty"`
	Centroid      *PythagoreanPoint      `protobuf:"bytes,3,opt,name=centroid,proto3" json:"centroid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythagoreanGroup) Reset() {
	*x = PythagoreanGroup{}
	mi := &file_models_pythagorean_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythagoreanGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythagoreanGroup) ProtoMessage() {}

func (x *PythagoreanGroup) ProtoReflect() protoreflect.Message {
	mi := &file_models_pythagorean_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythagoreanGroup.ProtoReflect.Descriptor instead.
func (*PythagoreanGroup) Descriptor() ([]byte, []int) {
	return file_models_pythagorean_proto_rawDescGZIP(), []int{1}
}

func (x *PythagoreanGroup) GetPoints() []*PythagoreanPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *PythagoreanGroup) GetNPoints() int32 {
	if x != nil {
		return x.NPoints
	}
	return 0
}

func (x *PythagoreanGroup) GetCentroid() *PythagoreanPoint {
	if x != nil {
		return x.Centroid
	}
	return nil
}

type PythagoreanPointStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Probability   float64                `protobuf:"fixed64,1,opt,name=probability,proto3" json:"probability,omitempty"`
	Distance      float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Point         *PythagoreanPoint      `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythagoreanPointStatus) Reset() {
	*x = PythagoreanPointStatus{}
	mi := &file_models_pythagorean_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythagoreanPointStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythagoreanPointStatus) ProtoMessage() {}

func (x *PythagoreanPointStatus) ProtoReflect() protoreflect.Message {
	mi := &file_models_pythagorean_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythagoreanPointStatus.ProtoReflect.Descriptor instead.
func (*PythagoreanPointStatus) Descriptor() ([]byte, []int) {
	return file_models_pythagorean_proto_rawDescGZIP(), []int{2}
}

func (x *PythagoreanPointStatus) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *PythagoreanPointStatus) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *PythagoreanPointStatus) GetPoint() *PythagoreanPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type PythagoreanNode struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	PointsStatus  []*PythagoreanPointStatus `protobuf:"bytes,1,rep,name=points_status,json=pointsStatus,proto3" json:"points_status,omitempty"`
	Centroid      *PythagoreanPoint         `protobuf:"bytes,2,opt,name=centroid,proto3" json:"centroid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythagoreanNode) Reset() {
	*x = PythagoreanNode{}
	mi := &file_models_pythagorean_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythagoreanNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythagoreanNode) ProtoMessage() {}

func (x *PythagoreanNode) ProtoReflect() protoreflect.Message {
	mi := &file_models_pythagorean_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythagoreanNode.ProtoReflect.Descriptor instead.
func (*PythagoreanNode) Descriptor() ([]byte, []int) {
	return file_models_pythagorean_proto_rawDescGZIP(), []int{3}
}

func (x *PythagoreanNode) GetPointsStatus() []*PythagoreanPointStatus {
	if x != nil {
		return x.PointsStatus
	}
	return nil
}

func (x *PythagoreanNode) GetCentroid() *PythagoreanPoint {
	if x != nil {
		return x.Centroid
	}
	return nil
}

type PythagoreanMainMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*PythagoreanNode     `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythagoreanMainMatrix) Reset() {
	*x = PythagoreanMainMatrix{}
	mi := &file_models_pythagorean_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythagoreanMainMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythagoreanMainMatrix) ProtoMessage() {}

func (x *PythagoreanMainMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_models_pythagorean_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythagoreanMainMatrix.ProtoReflect.Descriptor instead.
func (*PythagoreanMainMatrix) Descriptor() ([]byte, []int) {
	return file_models_pythagorean_proto_rawDescGZIP(), []int{4}
}

func (x *PythagoreanMainMatrix) GetNodes() []*PythagoreanNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PythagoreanSupportMachineInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*PythagoreanPoint    `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	NGroups       int32                  `protobuf:"varint,2,opt,name=n_groups,json=nGroups,proto3" json:"n_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythagoreanSupportMachineInput) Reset() {
	*x = PythagoreanSupportMachineInput{}
	mi := &file_models_pythagorean_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythagoreanSupportMachineInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythagoreanSupportMachineInput) ProtoMessage() {}

func (x *PythagoreanSupportMachineInput) ProtoReflect() protoreflect.Message {
	mi := &file_models_pythagorean_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythagoreanSupportMachineInput.ProtoReflect.Descriptor instead.
func (*PythagoreanSupportMachineInput) Descriptor() ([]byte, []int) {
	return file_models_pythagorean_proto_rawDescGZIP(), []int{5}
}

func (x *PythagoreanSupportMachineInput) GetPoints() []*PythagoreanPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *PythagoreanSupportMachineInput) GetNGroups() int32 {
	if x != nil {
		return x.NGroups
	}
	return 0
}

type PythagoreanSupportMachineOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*PythagoreanGroup    `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NDimensions   int32                  `protobuf:"varint,2,opt,name=n_dimensions,json=nDimensions,proto3" json:"n_dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythagoreanSupportMachineOutput) Reset() {
	*x = PythagoreanSupportMachineOutput{}
	mi := &file_models_pythagorean_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythagoreanSupportMachineOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythagoreanSupportMachineOutput) ProtoMessage() {}

func (x *PythagoreanSupportMachineOutput) ProtoReflect() protoreflect.Message {
	mi := &file_models_pythagorean_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythagoreanSupportMachineOutput.ProtoReflect.Descriptor instead.
func (*PythagoreanSupportMachineOutput) Descriptor() ([]byte, []int) {
	return file_models_pythagorean_proto_rawDescGZIP(), []int{6}
}

func (x *PythagoreanSupportMachineOutput) GetGroups() []*PythagoreanGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *PythagoreanSupportMachineOutput) GetNDimensions() int32 {
	if x != nil {
		return x.NDimensions
	}
	return 0
}

var File_models_pythagorean_proto protoreflect.FileDescriptor

const file_models_pythagorean_proto_rawDesc = "" +
	"\n" +
	"\x18models/pythagorean.proto\x12\tml_models\"4\n" +
	"\x10PythagoreanPoint\x12 \n" +
	"\vcoordinates\x18\x01 \x03(\x01R\vcoordinates\"\x9b\x01\n" +
	"\x10PythagoreanGroup\x123\n" +
	"\x06points\x18\x01 \x03(\v2\x1b.ml_models.PythagoreanPointR\x06points\x12\x19\n" +
	"\bn_points\x18\x02 \x01(\x05R\anPoints\x127\n" +
	"\bcentroid\x18\x03 \x01(\v2\x1b.ml_models.PythagoreanPointR\bcentroid\"\x89\x01\n" +
	"\x16PythagoreanPointStatus\x12 \n" +
	"\vprobability\x18\x01 \x01(\x01R\vprobability\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\x121\n" +
	"\x05point\x18\x03 \x01(\v2\x1b.ml_models.PythagoreanPointR\x05point\"\x92\x01\n" +
	"\x0fPythagoreanNode\x12F\n" +
	"\rpoints_status\x18\x01 \x03(\v2!.ml_models.PythagoreanPointStatusR\fpointsStatus\x127\n" +
	"\bcentroid\x18\x02 \x01(\v2\x1b.ml_models.PythagoreanPointR\bcentroid\"I\n" +
	"\x15PythagoreanMainMatrix\x120\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1a.ml_models.PythagoreanNodeR\x05nodes\"p\n" +
	"\x1ePythagoreanSupportMachineInput\x123\n" +
	"\x06points\x18\x01 \x03(\v2\x1b.ml_models.PythagoreanPointR\x06points\x12\x19\n" +
	"\bn_groups\x18\x02 \x01(\x05R\anGroups\"y\n" +
	"\x1fPythagoreanSupportMachineOutput\x123\n" +
	"\x06groups\x18\x01 \x03(\v2\x1b.ml_models.PythagoreanGroupR\x06groups\x12!\n" +
	"\fn_dimensions\x18\x02 \x01(\x05R\vnDimensionsB'Z%ml-models-api/protos/protos_go/modelsb\x06proto3"

var (
	file_models_pythagorean_proto_rawDescOnce sync.Once
	file_models_pythagorean_proto_rawDescData []byte
)

func file_models_pythagorean_proto_rawDescGZIP() []byte {
	file_models_pythagorean_proto_rawDescOnce.Do(func() {
		file_models_pythagorean_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_pythagorean_proto_rawDesc), len(file_models_pythagorean_proto_rawDesc)))
	})
	return file_models_pythagorean_proto_rawDescData
}

var file_models_pythagorean_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_models_pythagorean_proto_goTypes = []any{
	(*PythagoreanPoint)(nil),                // 0: ml_models.PythagoreanPoint
	(*PythagoreanGroup)(nil),                // 1: ml_models.PythagoreanGroup
	(*PythagoreanPointStatus)(nil),          // 2: ml_models.PythagoreanPointStatus
	(*PythagoreanNode)(nil),                 // 3: ml_models.PythagoreanNode
	(*PythagoreanMainMatrix)(nil),           // 4: ml_models.PythagoreanMainMatrix
	(*PythagoreanSupportMachineInput)(nil),  // 5: ml_models.PythagoreanSupportMachineInput
	(*PythagoreanSupportMachineOutput)(nil), // 6: ml_models.PythagoreanSupportMachineOutput
}
var file_models_pythagorean_proto_depIdxs = []int32{
	0, // 0: ml_models.PythagoreanGroup.points:type_name -> ml_models.PythagoreanPoint
	0, // 1: ml_models.PythagoreanGroup.centroid:type_name -> ml_models.PythagoreanPoint
	0, // 2: ml_models.PythagoreanPointStatus.point:type_name -> ml_models.PythagoreanPoint
	2, // 3: ml_models.PythagoreanNode.points_status:type_name -> ml_models.PythagoreanPointStatus
	0, // 4: ml_models.PythagoreanNode.centroid:type_name -> ml_models.PythagoreanPoint
	3, // 5: ml_models.PythagoreanMainMatrix.nodes:type_name -> ml_models.PythagoreanNode
	0, // 6: ml_models.PythagoreanSupportMachineInput.points:type_name -> ml_models.PythagoreanPoint
	1, // 7: ml_models.PythagoreanSupportMachineOutput.groups:type_name -> ml_models.PythagoreanGroup
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_models_pythagorean_proto_init() }
func file_models_pythagorean_proto_init() {
	if File_models_pythagorean_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_pythagorean_proto_rawDesc), len(file_models_pythagorean_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_pythagorean_proto_goTypes,
		DependencyIndexes: file_models_pythagorean_proto_depIdxs,
		MessageInfos:      file_models_pythagorean_proto_msgTypes,
	}.Build()
	File_models_pythagorean_proto = out.File
	file_models_pythagorean_proto_goTypes = nil
	file_models_pythagorean_proto_depIdxs = nil
}
