# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models/ant_colony.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'models/ant_colony.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17models/ant_colony.proto\x12\tml_models\"3\n\x0e\x41ntColonyPoint\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"\xc8\x01\n\x10\x41ntColonySegment\x12)\n\x06\x66rom_p\x18\x01 \x01(\x0b\x32\x19.ml_models.AntColonyPoint\x12\'\n\x04to_p\x18\x02 \x01(\x0b\x32\x19.ml_models.AntColonyPoint\x12\x10\n\x08\x64istance\x18\x03 \x01(\x01\x12\x16\n\tpheromone\x18\x04 \x01(\x01H\x00\x88\x01\x01\x12\x18\n\x0bprobability\x18\x05 \x01(\x01H\x01\x88\x01\x01\x42\x0c\n\n_pheromoneB\x0e\n\x0c_probability\"o\n\x0e\x41ntColonyTrail\x12-\n\x08segments\x18\x01 \x03(\x0b\x32\x1b.ml_models.AntColonySegment\x12\x1b\n\x0etotal_distance\x18\x02 \x01(\x01H\x00\x88\x01\x01\x42\x11\n\x0f_total_distance\"A\n\x14\x41ntColonyTrailMatrix\x12)\n\x06matrix\x18\x01 \x03(\x0b\x32\x19.ml_models.AntColonyTrail\"L\n\x1f\x41ntColonyCollectionOfAntsTrails\x12)\n\x06trails\x18\x01 \x03(\x0b\x32\x19.ml_models.AntColonyTrail\"-\n\x15\x41ntColonyPointRequest\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"D\n\x10\x41ntColonyRequest\x12\x30\n\x06points\x18\x01 \x03(\x0b\x32 .ml_models.AntColonyPointRequest\"\xc1\x01\n\x11\x41ntColonyResponse\x12.\n\x0b\x66irst_trail\x18\x01 \x01(\x0b\x32\x19.ml_models.AntColonyTrail\x12-\n\nlast_trail\x18\x02 \x01(\x0b\x32\x19.ml_models.AntColonyTrail\x12M\n\x19\x63ollection_of_ants_trails\x18\x03 \x01(\x0b\x32*.ml_models.AntColonyCollectionOfAntsTrailsB\'Z%ml-models-api/protos/protos_go/modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.ant_colony_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%ml-models-api/protos/protos_go/models'
  _globals['_ANTCOLONYPOINT']._serialized_start=38
  _globals['_ANTCOLONYPOINT']._serialized_end=89
  _globals['_ANTCOLONYSEGMENT']._serialized_start=92
  _globals['_ANTCOLONYSEGMENT']._serialized_end=292
  _globals['_ANTCOLONYTRAIL']._serialized_start=294
  _globals['_ANTCOLONYTRAIL']._serialized_end=405
  _globals['_ANTCOLONYTRAILMATRIX']._serialized_start=407
  _globals['_ANTCOLONYTRAILMATRIX']._serialized_end=472
  _globals['_ANTCOLONYCOLLECTIONOFANTSTRAILS']._serialized_start=474
  _globals['_ANTCOLONYCOLLECTIONOFANTSTRAILS']._serialized_end=550
  _globals['_ANTCOLONYPOINTREQUEST']._serialized_start=552
  _globals['_ANTCOLONYPOINTREQUEST']._serialized_end=597
  _globals['_ANTCOLONYREQUEST']._serialized_start=599
  _globals['_ANTCOLONYREQUEST']._serialized_end=667
  _globals['_ANTCOLONYRESPONSE']._serialized_start=670
  _globals['_ANTCOLONYRESPONSE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
