# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models/pythagorean.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'models/pythagorean.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18models/pythagorean.proto\x12\tml_models\"\'\n\x10PythagoreanPoint\x12\x13\n\x0b\x63oordinates\x18\x01 \x03(\x01\"\x80\x01\n\x10PythagoreanGroup\x12+\n\x06points\x18\x01 \x03(\x0b\x32\x1b.ml_models.PythagoreanPoint\x12\x10\n\x08n_points\x18\x02 \x01(\x05\x12-\n\x08\x63\x65ntroid\x18\x03 \x01(\x0b\x32\x1b.ml_models.PythagoreanPoint\"k\n\x16PythagoreanPointStatus\x12\x13\n\x0bprobability\x18\x01 \x01(\x01\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x12*\n\x05point\x18\x03 \x01(\x0b\x32\x1b.ml_models.PythagoreanPoint\"z\n\x0fPythagoreanNode\x12\x38\n\rpoints_status\x18\x01 \x03(\x0b\x32!.ml_models.PythagoreanPointStatus\x12-\n\x08\x63\x65ntroid\x18\x02 \x01(\x0b\x32\x1b.ml_models.PythagoreanPoint\"B\n\x15PythagoreanMainMatrix\x12)\n\x05nodes\x18\x01 \x03(\x0b\x32\x1a.ml_models.PythagoreanNode\"_\n\x1ePythagoreanSupportMachineInput\x12+\n\x06points\x18\x01 \x03(\x0b\x32\x1b.ml_models.PythagoreanPoint\x12\x10\n\x08n_groups\x18\x02 \x01(\x05\"d\n\x1fPythagoreanSupportMachineOutput\x12+\n\x06groups\x18\x01 \x03(\x0b\x32\x1b.ml_models.PythagoreanGroup\x12\x14\n\x0cn_dimensions\x18\x02 \x01(\x05\x42\'Z%ml-models-api/protos/protos_go/modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.pythagorean_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%ml-models-api/protos/protos_go/models'
  _globals['_PYTHAGOREANPOINT']._serialized_start=39
  _globals['_PYTHAGOREANPOINT']._serialized_end=78
  _globals['_PYTHAGOREANGROUP']._serialized_start=81
  _globals['_PYTHAGOREANGROUP']._serialized_end=209
  _globals['_PYTHAGOREANPOINTSTATUS']._serialized_start=211
  _globals['_PYTHAGOREANPOINTSTATUS']._serialized_end=318
  _globals['_PYTHAGOREANNODE']._serialized_start=320
  _globals['_PYTHAGOREANNODE']._serialized_end=442
  _globals['_PYTHAGOREANMAINMATRIX']._serialized_start=444
  _globals['_PYTHAGOREANMAINMATRIX']._serialized_end=510
  _globals['_PYTHAGOREANSUPPORTMACHINEINPUT']._serialized_start=512
  _globals['_PYTHAGOREANSUPPORTMACHINEINPUT']._serialized_end=607
  _globals['_PYTHAGOREANSUPPORTMACHINEOUTPUT']._serialized_start=609
  _globals['_PYTHAGOREANSUPPORTMACHINEOUTPUT']._serialized_end=709
# @@protoc_insertion_point(module_scope)
